# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apache',
            fields=[
                ('ApacheID', models.AutoField(serialize=False, verbose_name=b'ApacheID', primary_key=True)),
                ('Port', models.IntegerField(verbose_name=b'\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('SSLPort', models.IntegerField(verbose_name=b'SSL\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('DocmentRoot', models.CharField(max_length=128, verbose_name=b'DocmentRoot')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_apache',
                'verbose_name': 'Apache\u4fe1\u606f',
                'verbose_name_plural': 'Apache\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Appserver',
            fields=[
                ('AppServerID', models.AutoField(serialize=False, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', primary_key=True)),
                ('HostName', models.CharField(max_length=32, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d')),
                ('OsName', models.CharField(max_length=32, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f')),
                ('OSVersion', models.CharField(max_length=32, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x89\x88\xe6\x9c\xac')),
                ('CpuSpeed', models.CharField(max_length=32, verbose_name=b'CPU\xe4\xb8\xbb\xe9\xa2\x91')),
                ('CpuNum', models.IntegerField(verbose_name=b'CPU\xe6\x95\xb0\xe9\x87\x8f')),
                ('MemorySize', models.IntegerField(verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xef\xbc\x88\xe5\x8d\x95\xe4\xbd\x8d\xef\xbc\x9aM\xef\xbc\x89')),
                ('DiskSize', models.IntegerField(verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98\xef\xbc\x88\xe5\x8d\x95\xe4\xbd\x8d\xef\xbc\x9aM\xef\xbc\x89')),
                ('LBIP', models.CharField(max_length=32, verbose_name=b'\xe8\xb4\x9f\xe8\xbd\xbd\xe5\x9d\x87\xe8\xa1\xa1IP', blank=True)),
                ('ServiceIP', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1IP')),
                ('ServerIP', models.CharField(max_length=32, verbose_name=b'\xe8\x99\x9a\xe6\x8b\x9f\xe5\x8c\x96\xe9\x9b\x86\xe7\xbe\xa4/\xe5\xae\xbf\xe4\xb8\xbbIP')),
                ('Usage', models.CharField(blank=True, max_length=32, verbose_name=b'\xe5\x8a\x9f\xe8\x83\xbd\xe8\xaf\xb4\xe6\x98\x8e', choices=[(b'application', b'\xe5\xba\x94\xe7\x94\xa8'), (b'db', b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93'), (b'app&db', b'\xe5\xba\x94\xe7\x94\xa8&\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93')])),
                ('Remark', models.CharField(blank=True, help_text=b'\xe6\x8f\x8f\xe8\xbf\xb0\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x8e\xaf\xe5\xa2\x83:UAT1\xef\xbc\x8cUAT2\xe7\xad\x89', max_length=1024, verbose_name=b'\xe7\x8e\xaf\xe5\xa2\x83\xe5\x90\x8d\xe7\xa7\xb0', choices=[(b'ST', b'ST'), (b'UAT1', b'UAT1'), (b'UAT2', b'UAT2'), (b'UAT3', b'UAT3'), (b'MEMB', b'MEMB'), (b'peixun', b'\xe5\x9f\xb9\xe8\xae\xad')])),
                ('UpdateTime', models.DateField(verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_appserver',
                'verbose_name': '\u670d\u52a1\u5668\u8d44\u6e90\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u8d44\u6e90\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Cluser',
            fields=[
                ('CluserID', models.AutoField(serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7', primary_key=True)),
                ('VCenter', models.CharField(max_length=128, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad\xe5\xbf\x83')),
                ('CluserName', models.CharField(max_length=128, verbose_name=b'\xe9\x9b\x86\xe7\xbe\xa4\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_cluser',
                'verbose_name': '\u865a\u62df\u5316\u96c6\u7fa4',
                'verbose_name_plural': '\u865a\u62df\u5316\u96c6\u7fa4\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='CM_Application',
            fields=[
                ('AppID', models.AutoField(serialize=False, verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe7\xb3\xbb\xe7\xbb\x9fID', primary_key=True)),
                ('Category', models.CharField(help_text=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\xa4\xa7\xe7\xb1\xbb\xef\xbc\x9a \xe5\xa4\xae\xe8\xa1\x8c\xe3\x80\x81\xe4\xba\xa4\xe6\x98\x93\xe5\x90\x8e\xe3\x80\x81\xe6\x95\xb0\xe6\x8d\xae\xe5\xa4\x84\xe7\x90\x86\xe7\xad\x89', max_length=64, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x88\x86\xe7\xb1\xbb')),
                ('ChineseName', models.CharField(max_length=128, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe4\xb8\xad\xe6\x96\x87\xe5\x90\x8d')),
                ('EnglishName', models.CharField(max_length=64, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe8\x8b\xb1\xe6\x96\x87\xe5\x90\x8d')),
                ('UATVersion', models.CharField(max_length=32, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe7\x89\x88\xe6\x9c\xac\xe5\x8f\xb7')),
                ('ServiceType', models.CharField(max_length=64, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xad\x89\xe7\xba\xa7', choices=[(b'hexin', b'\xe6\xa0\xb8\xe5\xbf\x83'), (b'fuzhu', b'\xe8\xbe\x85\xe5\x8a\xa9'), (b'qita', b'\xe5\x85\xb6\xe4\xbb\x96')])),
                ('Status', models.CharField(max_length=64, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81', choices=[(b'shangxian', b'\xe4\xb8\x8a\xe7\xba\xbf'), (b'xiaxian', b'\xe4\xb8\x8b\xe7\xba\xbf'), (b'zhanting', b'\xe6\x9a\x82\xe5\x81\x9c')])),
                ('LaunchDate', models.DateField(verbose_name=b'\xe4\xb8\x8a\xe7\xba\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('OffDate', models.DateField(verbose_name=b'\xe4\xb8\x8b\xe7\xba\xbf\xe6\x97\xa5\xe6\x9c\x9f', blank=True)),
                ('ServiceStart', models.TimeField(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('ServiceEnd', models.TimeField(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('OperationStart', models.CharField(max_length=128, verbose_name=b'\xe7\xa6\x81\xe6\xad\xa2\xe5\x8f\x98\xe6\x9b\xb4\xe6\x97\xb6\xe9\x97\xb4\xe6\xae\xb5')),
                ('AvailableDate', models.CharField(max_length=128, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x97\xa5\xe6\x9c\x9f')),
                ('UatRelease', models.CharField(max_length=300, verbose_name=b'UAT\xe5\x8f\x91\xe5\xb8\x83\xe8\xb7\xaf\xe5\xbe\x84')),
                ('ProdRelease', models.CharField(max_length=300, verbose_name=b'\xe6\xa8\xa1\xe6\x8b\x9f\xe5\x8f\x91\xe5\xb8\x83\xe8\xb7\xaf\xe5\xbe\x84')),
                ('Description', models.CharField(max_length=500, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('Remark', models.CharField(max_length=500, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8', blank=True)),
                ('UpdateDate', models.DateField(verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_cm_application',
                'verbose_name': '\u5e94\u7528\u7cfb\u7edf\u914d\u7f6e\u4fe1\u606f',
                'verbose_name_plural': '\u5e94\u7528\u7cfb\u7edf\u914d\u7f6e\u57fa\u672c\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='CM_Application_Maintainer',
            fields=[
                ('ID', models.AutoField(serialize=False, verbose_name=b'ID', primary_key=True)),
                ('DeptName', models.CharField(max_length=64, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe9\x83\xa8\xe9\x97\xa8')),
                ('CMA', models.CharField(max_length=32, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xae\xe7\xae\xa1\xe7\x90\x86\xe5\xb2\x97A')),
                ('CMB', models.CharField(max_length=32, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xae\xe7\xae\xa1\xe7\x90\x86\xe5\xb2\x97B')),
                ('DeilverA', models.CharField(max_length=32, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe4\xba\xa4\xe4\xbb\x98\xe5\xb2\x97A')),
                ('DeilverB', models.CharField(max_length=32, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe4\xba\xa4\xe4\xbb\x98\xe5\xb2\x97B')),
                ('DevPM', models.CharField(max_length=32, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbb\x8f\xe7\x90\x86')),
                ('DevCompany', models.CharField(max_length=64, verbose_name=b'\xe5\xbc\x80\xe5\x8f\x91\xe5\x85\xac\xe5\x8f\xb8')),
                ('DevCompanyPM', models.CharField(max_length=32, verbose_name=b'\xe5\xbc\x80\xe5\x8f\x91\xe5\x85\xac\xe5\x8f\xb8\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba')),
                ('TestPM', models.CharField(max_length=32, verbose_name=b'\xe7\xac\xac\xe4\xb8\x89\xe6\x96\xb9\xe6\xb5\x8b\xe8\xaf\x95\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba')),
                ('TestLD', models.CharField(max_length=32, verbose_name=b'\xe7\xac\xac\xe4\xb8\x89\xe6\x96\xb9\xe6\xb5\x8b\xe8\xaf\x95\xe7\xbb\x84\xe9\x95\xbf')),
                ('AppID', models.ForeignKey(verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe7\xb3\xbb\xe7\xbb\x9fID', to='cm_vrms_wiki.CM_Application')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_cm_application_maintainer',
                'verbose_name': '\u5e94\u7528\u7cfb\u7edf\u914d\u7f6e\u4eba\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u5e94\u7528\u7cfb\u7edf\u914d\u7f6e\u4eba\u5458\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='CM_Users',
            fields=[
                ('UserID', models.AutoField(serialize=False, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7ID', primary_key=True)),
                ('UserName', models.CharField(max_length=32, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('UserType', models.CharField(max_length=32, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe7\xb1\xbb\xe5\x88\xab', choices=[(b'application', b'\xe5\xba\x94\xe7\x94\xa8\xe7\x94\xa8\xe6\x88\xb7'), (b'db', b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\x94\xa8\xe6\x88\xb7'), (b'app&db', b'\xe5\xba\x94\xe7\x94\xa8&\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\x94\xa8\xe6\x88\xb7')])),
                ('ExpirationDate', models.DateField(help_text=b'\xe6\xb0\xb8\xe4\xb8\x8d\xe5\x88\xb0\xe6\x9c\x9f\xef\xbc\x8c\xe7\x94\xa8\xe2\x80\x9c9999-12-31\xe2\x80\x9d\xe8\xa1\xa8\xe7\xa4\xba', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x88\xb0\xe6\x9c\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('PGroupName', models.CharField(max_length=32, verbose_name=b'\xe4\xb8\xbb\xe7\xbb\x84')),
                ('SGroupName', models.CharField(max_length=64, verbose_name=b'\xe9\x99\x84\xe5\xb1\x9e\xe7\xbb\x84', blank=True)),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_cm_users',
                'verbose_name': '\u7cfb\u7edf\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7cfb\u7edf\u7528\u6237\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Config_File',
            fields=[
                ('ConfigId', models.AutoField(serialize=False, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xaeID', primary_key=True)),
                ('ConfigName', models.CharField(max_length=256, verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe9\x85\x8d\xe7\xbd\xae\xe6\x96\x87\xe4\xbb\xb6\xe5\x90\x8d')),
                ('ConfigDescription', models.CharField(max_length=2048, verbose_name=b'\xe5\x8f\x82\xe6\x95\xb0\xe8\xaf\xb4\xe6\x98\x8e', blank=True)),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
                ('UserID', models.ForeignKey(verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7ID', to='cm_vrms_wiki.CM_Users')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_config_file',
                'verbose_name': '\u670d\u52a1\u5668\u914d\u7f6e\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u914d\u7f6e\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Config_Item',
            fields=[
                ('ConfigItemId', models.AutoField(serialize=False, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xae\xe9\xa1\xb9ID', primary_key=True)),
                ('Parameter', models.CharField(max_length=256, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xae\xe9\xa1\xb9')),
                ('value', models.CharField(max_length=256, verbose_name=b'\xe9\x85\x8d\xe7\xbd\xae\xe5\x80\xbc')),
                ('bl1', models.BooleanField(verbose_name=b'\xe5\x90\x8c\xe4\xb8\x80\xe7\x89\x88\xe6\x9c\xac\xe4\xb8\x8d\xe5\x90\x8c\xe7\x8e\xaf\xe5\xa2\x83\xe6\x98\xaf\xe5\x90\xa6\xe7\x9b\xb8\xe5\x90\x8c')),
                ('bl2', models.BooleanField(verbose_name=b'\xe4\xb8\x8d\xe5\x90\x8c\xe7\x89\x88\xe6\x9c\xac\xe7\x9b\xb8\xe5\x90\x8c\xe7\x8e\xaf\xe5\xa2\x83\xe6\x98\xaf\xe5\x90\xa6\xe7\x9b\xb8\xe5\x90\x8c')),
                ('ConfigDescription', models.CharField(max_length=2048, verbose_name=b'\xe5\x8f\x82\xe6\x95\xb0\xe8\xaf\xb4\xe6\x98\x8e', blank=True)),
                ('ConfigName', models.ForeignKey(verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe9\x85\x8d\xe7\xbd\xae\xe6\x96\x87\xe4\xbb\xb6\xe5\x90\x8d', to='cm_vrms_wiki.Config_File')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_config_item',
                'verbose_name': '\u670d\u52a1\u5668\u914d\u7f6e\u9879\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u914d\u7f6e\u9879\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='DB',
            fields=[
                ('DBID', models.AutoField(serialize=False, verbose_name=b'DBID', primary_key=True)),
                ('INSTANCE_NAME', models.CharField(max_length=32, verbose_name=b'\xe5\xae\x9e\xe4\xbe\x8b\xe5\x90\x8d')),
                ('DBName', models.CharField(max_length=32, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x90\x8d')),
                ('DataFile', models.CharField(max_length=128, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe6\x96\x87\xe4\xbb\xb6\xe8\xb7\xaf\xe5\xbe\x84', blank=True)),
                ('LogFile', models.CharField(max_length=128, verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97\xe6\x96\x87\xe4\xbb\xb6\xe8\xb7\xaf\xe5\xbe\x84', blank=True)),
                ('Port', models.CharField(max_length=32, verbose_name=b'\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('DbUser', models.CharField(max_length=32, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\x94\xa8\xe6\x88\xb7')),
                ('HA', models.CharField(max_length=32, verbose_name=b'\xe9\xab\x98\xe5\x8f\xaf\xe7\x94\xa8\xe6\xa8\xa1\xe5\xbc\x8f', choices=[(b'Y', b'\xe6\x98\xaf'), (b'N', b'\xe5\x90\xa6')])),
                ('MEMBER', models.CharField(max_length=128, verbose_name=b'\xe7\xbb\x84\xe5\x91\x98')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_db',
                'verbose_name': '\u6570\u636e\u5e93\u4fe1\u606f',
                'verbose_name_plural': '\u6570\u636e\u5e93\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('DeviceID', models.AutoField(serialize=False, verbose_name=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba\xe7\xbc\x96\xe5\x8f\xb7', primary_key=True)),
                ('DeviceSN', models.CharField(max_length=128, verbose_name=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('MANUFACTURER', models.CharField(max_length=64, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe5\x8e\x82\xe5\x95\x86')),
                ('CATEGORY', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xb1\xbb\xe5\x88\xab', choices=[(b'server', b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (b'storage', b'\xe5\xad\x98\xe5\x82\xa8'), (b'network', b'\xe7\xbd\x91\xe7\xbb\x9c\xe8\xae\xbe\xe5\xa4\x87'), (b'equiment', b'\xe6\x9c\xba\xe6\x88\xbf\xe8\xae\xbe\xe5\xa4\x87')])),
                ('PURCHASE_DATE', models.DateField(verbose_name=b'\xe8\xb4\xad\xe7\xbd\xae\xe6\x97\xa5\xe6\x9c\x9f')),
                ('maintainerA', models.CharField(max_length=32, verbose_name=b'\xe8\xbf\x90\xe7\xbb\xb4A')),
                ('maintainerB', models.CharField(max_length=32, verbose_name=b'\xe8\xbf\x90\xe7\xbb\xb4B')),
                ('DISTRICT', models.CharField(max_length=32, verbose_name=b'\xe5\x8c\xba\xe5\x9f\x9f')),
                ('ROOM', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf')),
                ('CABINET', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c')),
                ('COUNT_U', models.CharField(max_length=32, verbose_name=b'U\xe6\x95\xb0')),
                ('REMARK', models.CharField(max_length=1024, verbose_name=b'\xe5\x8a\x9f\xe7\x8e\x87\xe8\xb4\x9f\xe8\xbd\xbd', blank=True)),
                ('UpdateTime', models.DateField(verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_device',
                'verbose_name': '\u7269\u7406\u8bbe\u5907\u4fe1\u606f',
                'verbose_name_plural': '\u7269\u7406\u8bbe\u5907\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Equipment_detail',
            fields=[
                ('EquipmentId', models.AutoField(serialize=False, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87ID', primary_key=True)),
                ('DeviceSN', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('Description', models.CharField(max_length=1024, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0', blank=True)),
                ('DeviceID', models.ForeignKey(verbose_name=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Device')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_equipment_detail',
                'verbose_name': '\u673a\u623f\u5176\u4ed6\u8bbe\u5907\u4fe1\u606f',
                'verbose_name_plural': '\u673a\u623f\u5176\u4ed6\u8bbe\u5907\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='LB',
            fields=[
                ('LBID', models.AutoField(serialize=False, verbose_name=b'\xe8\xb4\x9f\xe8\xbd\xbd\xe5\x9d\x87\xe8\xa1\xa1ID', primary_key=True)),
                ('LBName', models.CharField(max_length=64, verbose_name=b'\xe8\xb4\x9f\xe8\xbd\xbd\xe5\x9d\x87\xe8\xa1\xa1\xe5\x90\x8d\xe7\xa7\xb0')),
                ('LBIP', models.CharField(max_length=32, verbose_name=b'\xe8\xb4\x9f\xe8\xbd\xbd\xe5\x9d\x87\xe8\xa1\xa1IP')),
                ('AppID', models.ForeignKey(verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe7\xb3\xbb\xe7\xbb\x9fID', to='cm_vrms_wiki.CM_Application')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_lb',
                'verbose_name': '\u5e94\u7528\u670d\u52a1\u5668\u96c6\u7fa4\u4fe1\u606f',
                'verbose_name_plural': '\u5e94\u7528\u670d\u52a1\u5668\u96c6\u7fa4\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='LB_Member',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('AppServerIP', models.CharField(max_length=64, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8IP')),
                ('AppID', models.ForeignKey(verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe7\xb3\xbb\xe7\xbb\x9fID', to='cm_vrms_wiki.CM_Application')),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
                ('LBID', models.ForeignKey(verbose_name=b'\xe8\xb4\x9f\xe8\xbd\xbd\xe5\x9d\x87\xe8\xa1\xa1ID', to='cm_vrms_wiki.LB')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_lb_member',
                'verbose_name': '\u5e94\u7528\u670d\u52a1\u5668\u7ec4\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u5e94\u7528\u670d\u52a1\u5668\u7ec4\u5458\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('LicenseID', models.AutoField(serialize=False, verbose_name=b'LicenseID', primary_key=True)),
                ('Software', models.CharField(max_length=256, verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6\xe5\x90\x8d\xe7\xa7\xb0')),
                ('Version', models.CharField(max_length=32, verbose_name=b'\xe7\x89\x88\xe6\x9c\xac')),
                ('DueDate', models.DateField(verbose_name=b'\xe5\x88\xb0\xe6\x9c\x9f\xe6\x97\xa5')),
                ('Company', models.CharField(max_length=64, verbose_name=b'\xe5\x8e\x82\xe5\x95\x86')),
                ('Remark', models.CharField(max_length=128, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8', blank=True)),
                ('AppID', models.ForeignKey(verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe7\xb3\xbb\xe7\xbb\x9fID', to='cm_vrms_wiki.CM_Application')),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_license',
                'verbose_name': '\u8bb8\u53ef\u8bc1\u4fe1\u606f',
                'verbose_name_plural': '\u8bb8\u53ef\u8bc1\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Log_File',
            fields=[
                ('LogId', models.AutoField(serialize=False, verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97ID', primary_key=True)),
                ('LogPath', models.CharField(max_length=256, verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97\xe6\x89\x80\xe5\x9c\xa8\xe7\x9b\xae\xe5\xbd\x95')),
                ('LogDescription', models.CharField(max_length=256, verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97\xe5\x86\x85\xe5\xae\xb9\xe8\xaf\xb4\xe6\x98\x8e', blank=True)),
                ('LifeCycle', models.CharField(max_length=512, verbose_name=b'\xe5\xae\x9a\xe6\x9c\x9f\xe7\xbb\xb4\xe6\x8a\xa4\xe8\xaf\xb4\xe6\x98\x8e', blank=True)),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
                ('UserID', models.ForeignKey(verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7ID', to='cm_vrms_wiki.CM_Users')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_log_file',
                'verbose_name': '\u670d\u52a1\u5668\u65e5\u5fd7\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u65e5\u5fd7\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('MountID', models.AutoField(serialize=False, verbose_name=b'\xe6\x8c\x82\xe8\xbd\xbd\xe7\x82\xb9ID', primary_key=True)),
                ('MountPath', models.CharField(max_length=128, verbose_name=b'\xe5\xa4\x96\xe6\x8e\xa5\xe5\xad\x98\xe5\x82\xa8\xe6\x8c\x82\xe8\xbd\xbd\xe7\x82\xb9')),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_mount',
                'verbose_name': '\u5b58\u50a8\u6302\u8f7d\u70b9\u4fe1\u606f',
                'verbose_name_plural': '\u5b58\u50a8\u6302\u8f7d\u70b9\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='MQ',
            fields=[
                ('MQID', models.AutoField(serialize=False, verbose_name=b'MQID', primary_key=True)),
                ('QueueManager', models.CharField(max_length=32, verbose_name=b'\xe9\x98\x9f\xe5\x88\x97\xe7\xae\xa1\xe7\x90\x86\xe5\x99\xa8\xe5\x90\x8d')),
                ('QLocal', models.CharField(max_length=32, verbose_name=b'\xe6\x9c\xac\xe5\x9c\xb0\xe9\x98\x9f\xe5\x88\x97\xe5\x90\x8d')),
                ('QRemote', models.CharField(max_length=32, verbose_name=b'\xe8\xbf\x9c\xe7\xa8\x8b\xe9\x98\x9f\xe5\x88\x97\xe5\x90\x8d')),
                ('Chanel', models.CharField(max_length=32, verbose_name=b'\xe9\x80\x9a\xe9\x81\x93')),
                ('Port', models.IntegerField(verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_mq',
                'verbose_name': '\u6d88\u606f\u961f\u5217\uff08MQ\uff09\u4fe1\u606f',
                'verbose_name_plural': '\u6d88\u606f\u961f\u5217\uff08MQ\uff09\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='NetDevice_detail',
            fields=[
                ('NetDeviceId', models.AutoField(serialize=False, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87ID', primary_key=True)),
                ('DeviceSN', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('NetDeviceType', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('MANAGE_IP', models.CharField(max_length=32, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86\xe5\x9c\xb0\xe5\x9d\x80')),
                ('IOS_VERSION', models.CharField(max_length=32, verbose_name=b'IOS\xe7\x89\x88\xe6\x9c\xac')),
                ('DeviceID', models.ForeignKey(verbose_name=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Device')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_netdevice_detail',
                'verbose_name': '\u7f51\u7edc\u8bbe\u5907\u4fe1\u606f',
                'verbose_name_plural': '\u7f51\u7edc\u8bbe\u5907\u8be6\u7ec6\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('OtherID', models.AutoField(serialize=False, verbose_name=b'OtherID', primary_key=True)),
                ('Description', models.CharField(max_length=1024, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_other',
                'verbose_name': '\u5176\u4ed6\u5e94\u7528\u4fe1\u606f',
                'verbose_name_plural': '\u5176\u4ed6\u5e94\u7528\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='server_detail',
            fields=[
                ('ServerId', models.AutoField(serialize=False, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8ID', primary_key=True)),
                ('ServerName', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x90\x8d')),
                ('DeviceSN', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('Server_type', models.CharField(max_length=64, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xb1\xbb\xe5\x9e\x8b', choices=[(b'pcserver', b'pc\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (b'xiaoxinji', b'\xe5\xb0\x8f\xe5\x9e\x8b\xe6\x9c\xba')])),
                ('CPU_TYPE', models.CharField(max_length=32, verbose_name=b'cpu\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('CPU_FREQUENCY', models.CharField(max_length=32, verbose_name=b'cpu\xe6\xa0\xb8\xe5\xbf\x83\xe9\xa2\x91\xe7\x8e\x87')),
                ('CPU_NUM', models.IntegerField(verbose_name=b'CPU\xe7\x89\xa9\xe7\x90\x86\xe4\xb8\xaa\xe6\x95\xb0')),
                ('CPU_CORE_NUM', models.IntegerField(verbose_name=b'\xe6\x80\xbb\xe7\x89\xa9\xe7\x90\x86CPU\xe6\xa0\xb8\xe5\xbf\x83\xe6\x95\xb0')),
                ('MEM_TYPE', models.CharField(max_length=32, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('MEM_CONF', models.CharField(help_text=b'\xe6\xa0\xbc\xe5\xbc\x8f\xef\xbc\x9a1G*2+2G*2\xef\xbc\x8c\xe8\xa1\xa8\xe7\xa4\xba\xe5\xae\xb9\xe9\x87\x8f*\xe6\x95\xb0\xe9\x87\x8f', max_length=1024, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe7\xbb\x84\xe6\x88\x90')),
                ('MEM_SIZE', models.CharField(max_length=32, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\x8f\xaf\xe7\x94\xa8\xe5\xae\xb9\xe9\x87\x8f')),
                ('HARDDISK_CAPACITY', models.CharField(help_text=b'\xe6\xa0\xbc\xe5\xbc\x8f\xef\xbc\x9a146G*2\xef\xbc\x88RAID1\xef\xbc\x89+300G*2\xef\xbc\x88RAID1\xef\xbc\x89\xef\xbc\x8c\xe8\xa1\xa8\xe7\xa4\xba\xe5\xae\xb9\xe9\x87\x8f*\xe6\x95\xb0\xe9\x87\x8f(RAID)', max_length=1024, verbose_name=b'\xe7\xa1\xac\xe7\x9b\x98\xe7\xbb\x84\xe6\x88\x90')),
                ('DISK_SIZE', models.CharField(max_length=32, verbose_name=b'\xe7\xa1\xac\xe7\x9b\x98\xe5\x8f\xaf\xe7\x94\xa8\xe5\xae\xb9\xe9\x87\x8f')),
                ('NETWORK_CARD', models.CharField(max_length=1024, verbose_name=b'\xe7\xbd\x91\xe5\x8d\xa1\xe7\xbb\x84\xe6\x88\x90')),
                ('HBACARD', models.CharField(max_length=1024, verbose_name=b'\xe5\x85\x89\xe7\xba\xa4\xe5\x8d\xa1\xe7\xbb\x84\xe6\x88\x90')),
                ('DeviceID', models.ForeignKey(verbose_name=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Device')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_server_detail',
                'verbose_name': '\u670d\u52a1\u5668\u8be6\u7ec6\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u8be6\u7ec6\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Server_Process_Pool',
            fields=[
                ('ProcessId', models.AutoField(serialize=False, verbose_name=b'\xe8\xbf\x9b\xe7\xa8\x8bID', primary_key=True)),
                ('ProcessName', models.CharField(max_length=64, verbose_name=b'\xe8\xbf\x9b\xe7\xa8\x8b\xe5\x90\x8d')),
                ('Port', models.IntegerField(verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3\xe5\x8f\xb7')),
                ('Function', models.CharField(max_length=256, verbose_name=b'\xe5\x8a\x9f\xe8\x83\xbd\xe8\xaf\xb4\xe6\x98\x8e', blank=True)),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
                ('UserID', models.ForeignKey(verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7ID', to='cm_vrms_wiki.CM_Users')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_server_process_pool',
                'verbose_name': '\u670d\u52a1\u5668\u8fdb\u7a0b\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u8fdb\u7a0b\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('SoftwareID', models.AutoField(serialize=False, verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6ID', primary_key=True)),
                ('SoftwareType', models.CharField(max_length=24, verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6\xe7\xb1\xbb\xe5\x9e\x8b', choices=[(b'weblogic', b'weblogic'), (b'DB', b'DB'), (b'MQ', b'MQ'), (b'Tomcat', b'Tomcat'), (b'Appache', b'Appache'), (b'Other', b'Other')])),
                ('SoftwareName', models.CharField(max_length=32, verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6\xe5\x90\x8d')),
                ('InstallPath', models.CharField(max_length=256, verbose_name=b'\xe5\xae\x89\xe8\xa3\x85\xe8\xb7\xaf\xe5\xbe\x84')),
                ('Version', models.CharField(max_length=32, verbose_name=b'\xe7\x89\x88\xe6\x9c\xac\xe5\x8f\xb7')),
                ('AppServerID', models.ForeignKey(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Appserver')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_software',
                'verbose_name': '\u8f6f\u4ef6\u4fe1\u606f',
                'verbose_name_plural': '\u8f6f\u4ef6\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='storage_detail',
            fields=[
                ('StorageId', models.AutoField(serialize=False, verbose_name=b'\xe5\xad\x98\xe5\x82\xa8ID', primary_key=True)),
                ('STORAGE_NAME', models.CharField(max_length=32, verbose_name=b'\xe5\xad\x98\xe5\x82\xa8\xe5\x90\x8d')),
                ('DeviceSN', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('Firmware', models.CharField(max_length=64, verbose_name=b'\xe5\xbe\xae\xe7\xa0\x81')),
                ('Ctlr_NUM', models.IntegerField(verbose_name=b'\xe6\x8e\xa7\xe5\x88\xb6\xe5\x99\xa8\xe6\x95\xb0')),
                ('DISK_TYPE', models.CharField(max_length=32, verbose_name=b'DISK\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('DISK_Capacity', models.CharField(max_length=32, verbose_name=b'DISK\xe5\xae\xb9\xe9\x87\x8f')),
                ('DISK_NUM', models.CharField(max_length=32, verbose_name=b'DISK\xe6\x95\xb0\xe9\x87\x8f')),
                ('IP', models.CharField(max_length=32, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86IP')),
                ('EXPANSIBILITY', models.CharField(max_length=32, verbose_name=b'\xe6\x89\xa9\xe5\xb1\x95\xe6\x9f\x9c', choices=[(b'Y', b'\xe6\x98\xaf'), (b'N', b'\xe5\x90\xa6')])),
                ('DeviceID', models.ForeignKey(verbose_name=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba\xe7\xbc\x96\xe5\x8f\xb7', to='cm_vrms_wiki.Device')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_storage_detail',
                'verbose_name': '\u5b58\u50a8\u4fe1\u606f',
                'verbose_name_plural': '\u5b58\u50a8\u8be6\u7ec6\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Tomcat',
            fields=[
                ('TomcatID', models.AutoField(serialize=False, verbose_name=b'TomcatID', primary_key=True)),
                ('Port', models.IntegerField(verbose_name=b'\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('SSLPort', models.IntegerField(verbose_name=b'SSL\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('DocmentRoot', models.CharField(max_length=128, verbose_name=b'DocmentRoot')),
                ('SoftwareID', models.ForeignKey(verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6ID', to='cm_vrms_wiki.Software')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_tomcat',
                'verbose_name': 'Tomcat\u4fe1\u606f',
                'verbose_name_plural': 'Tomcat\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Weblogic',
            fields=[
                ('WeblogicID', models.AutoField(serialize=False, verbose_name=b'WeblogicID', primary_key=True)),
                ('ConsoleContexPath', models.CharField(max_length=128, verbose_name=b'\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xb7\xaf\xe5\xbe\x84')),
                ('ConsoleUserName', models.CharField(max_length=24, verbose_name=b'\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xb4\xa6\xe5\x8f\xb7')),
                ('DomianName', models.CharField(max_length=32, verbose_name=b'\xe5\x9f\x9f\xe5\x90\x8d')),
                ('DomainPath', models.CharField(max_length=128, verbose_name=b'\xe5\x9f\x9f\xe8\xb7\xaf\xe5\xbe\x84')),
                ('WeblogicServerName', models.CharField(max_length=32, verbose_name=b'WeblogicServer\xe5\x90\x8d')),
                ('Listener', models.CharField(max_length=32, verbose_name=b'\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('SSLListener', models.CharField(max_length=32, verbose_name=b'SSL\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('JDBCType', models.CharField(max_length=64, verbose_name=b'JDBC\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('JNDIName', models.CharField(max_length=64, verbose_name=b'JNDI\xe5\x90\x8d')),
                ('JDBCUrl', models.CharField(max_length=64, verbose_name=b'JDBCUrl')),
                ('Driver', models.CharField(max_length=64, verbose_name=b'\xe9\xa9\xb1\xe5\x8a\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('SoftwareID', models.ForeignKey(verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6ID', to='cm_vrms_wiki.Software')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_weblogic',
                'verbose_name': 'weblogic\u4fe1\u606f',
                'verbose_name_plural': 'weblogic\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Weblogic_App',
            fields=[
                ('AppID', models.AutoField(serialize=False, verbose_name=b'AppID', primary_key=True)),
                ('AppName', models.CharField(max_length=32, verbose_name=b'WebApp\xe5\x90\x8d')),
                ('DeployPath', models.CharField(max_length=128, verbose_name=b'WebApp\xe9\x83\xa8\xe7\xbd\xb2\xe8\xb7\xaf\xe5\xbe\x84')),
                ('DeployType', models.CharField(max_length=32, verbose_name=b'\xe9\x83\xa8\xe7\xbd\xb2\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('Description', models.CharField(max_length=256, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0\xe4\xbf\xa1\xe6\x81\xaf', blank=True)),
            ],
            options={
                'db_table': 'cm_vrms_wiki_weblogic_app',
                'verbose_name': 'weblogic\u5e94\u7528\u90e8\u7f72\u4fe1\u606f',
                'verbose_name_plural': 'weblogic\u5e94\u7528\u90e8\u7f72\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Weblogic_Jdbc',
            fields=[
                ('JdbcID', models.AutoField(serialize=False, verbose_name=b'JDBCID', primary_key=True)),
                ('JDBCType', models.CharField(max_length=64, verbose_name=b'JDBC\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('JNDIName', models.CharField(max_length=64, verbose_name=b'JNDI\xe5\x90\x8d')),
                ('JDBCUrl', models.CharField(max_length=64, verbose_name=b'JDBCUrl')),
                ('Driver', models.CharField(max_length=64, verbose_name=b'\xe9\xa9\xb1\xe5\x8a\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('WeblogicID', models.ForeignKey(verbose_name=b'WeblogicID', to='cm_vrms_wiki.Weblogic')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_weblogic_jdbc',
                'verbose_name': 'weblogic_JDBC\u4fe1\u606f',
                'verbose_name_plural': 'weblogic_JDBC\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Weblogic_Jdbc_Map',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('JdbcID', models.ForeignKey(verbose_name=b'JDBCID', to='cm_vrms_wiki.Weblogic_Jdbc')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_weblogic_jdbc_map',
                'verbose_name': 'weblogic_jdbc\u6620\u5c04\u4fe1\u606f',
                'verbose_name_plural': 'weblogic_jdbc\u6620\u5c04\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Weblogic_Server',
            fields=[
                ('ServerID', models.AutoField(serialize=False, verbose_name=b'ServerID', primary_key=True)),
                ('WeblogicServerName', models.CharField(max_length=32, verbose_name=b'WeblogicServer\xe5\x90\x8d')),
                ('Listener', models.CharField(max_length=32, verbose_name=b'\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('SSLListener', models.CharField(max_length=32, verbose_name=b'SSL\xe7\x9b\x91\xe5\x90\xac\xe7\xab\xaf\xe5\x8f\xa3')),
                ('WeblogicID', models.ForeignKey(verbose_name=b'WeblogicID', to='cm_vrms_wiki.Weblogic')),
            ],
            options={
                'db_table': 'cm_vrms_wiki_weblogic_server',
                'verbose_name': 'weblogic_server\u4fe1\u606f',
                'verbose_name_plural': 'weblogic_server\u4fe1\u606f\u8868',
            },
        ),
        migrations.AddField(
            model_name='weblogic_jdbc_map',
            name='ServerID',
            field=models.ForeignKey(verbose_name=b'ServerID', to='cm_vrms_wiki.Weblogic_Server'),
        ),
        migrations.AddField(
            model_name='weblogic_app',
            name='ServerID',
            field=models.ForeignKey(verbose_name=b'ServerID', to='cm_vrms_wiki.Weblogic_Server'),
        ),
        migrations.AddField(
            model_name='other',
            name='SoftwareID',
            field=models.ForeignKey(verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6ID', to='cm_vrms_wiki.Software'),
        ),
        migrations.AddField(
            model_name='mq',
            name='SoftwareID',
            field=models.ForeignKey(verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6ID', to='cm_vrms_wiki.Software'),
        ),
        migrations.AddField(
            model_name='mount',
            name='StorageDeviceId',
            field=models.ForeignKey(verbose_name=b'\xe5\xad\x98\xe5\x82\xa8ID', to='cm_vrms_wiki.storage_detail'),
        ),
        migrations.AddField(
            model_name='db',
            name='SoftwareID',
            field=models.ForeignKey(verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6ID', to='cm_vrms_wiki.Software'),
        ),
        migrations.AddField(
            model_name='appserver',
            name='AppID',
            field=models.ForeignKey(verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe7\xb3\xbb\xe7\xbb\x9fID', blank=True, to='cm_vrms_wiki.CM_Application', null=True),
        ),
        migrations.AddField(
            model_name='appserver',
            name='CluserID',
            field=models.ForeignKey(verbose_name=b'\xe9\x9b\x86\xe7\xbe\xa4\xe5\x90\x8d\xe7\xa7\xb0', blank=True, to='cm_vrms_wiki.Cluser', null=True),
        ),
        migrations.AddField(
            model_name='appserver',
            name='DeviceID',
            field=models.ForeignKey(verbose_name=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba\xe7\xbc\x96\xe5\x8f\xb7', blank=True, to='cm_vrms_wiki.Device', null=True),
        ),
        migrations.AddField(
            model_name='apache',
            name='SoftwareID',
            field=models.ForeignKey(verbose_name=b'\xe8\xbd\xaf\xe4\xbb\xb6ID', to='cm_vrms_wiki.Software'),
        ),
    ]
